# Generated by Django 3.1.14 on 2023-10-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpm', '0002_auto_20231001_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='last_action',
            field=models.IntegerField(blank=True, choices=[(0, 'created'), (1, 'deleted')], null=True, verbose_name='last_action'),
        ),
    ]
