# Generated by Django 3.1.14 on 2023-10-11 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpm', '0003_peer_last_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='last_action',
            field=models.IntegerField(choices=[(0, 'created'), (1, 'deleted')], default=0, verbose_name='last_action'),
        ),
        migrations.AlterField(
            model_name='peer',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Only upper/lowercase letters and numbers. Up to 32 characters allowed.', regex='^[A-Za-z0-9]{1,32}$')], verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='peer',
            unique_together={('name', 'endpoint')},
        ),
    ]
